### ISSUE TITLE
TypeError from get_token.client_credentials using v3.2.0 and py2.7

### ISSUE THREAD

**Issue by faria** [auth0/auth0-python#101]
I am on python2.7. The get_token.client_credentials has always worked for me using v3.1.4. 
I upgraded to 3.2.0 and I get the following error when calling client_credentials:

File "/Users/faria/w/nsplab/orbit-server/scripts/auth0_users.py", line 19, in connect
    token = get_token.client_credentials(client_id, client_secret, mgmt_url)
  File "/Users/faria/.virtualenvs/orbit/lib/python2.7/site-packages/auth0/v3/authentication/get_token.py", line 120, in client_credentials
    headers={'Content-Type': 'application/json'}
  File "/Users/faria/.virtualenvs/orbit/lib/python2.7/site-packages/auth0/v3/authentication/base.py", line 12, in post
    return self._process_response(response)
  File "/Users/faria/.virtualenvs/orbit/lib/python2.7/site-packages/auth0/v3/authentication/base.py", line 18, in _process_response
    return self._parse(response).content()
  File "/Users/faria/.virtualenvs/orbit/lib/python2.7/site-packages/auth0/v3/authentication/base.py", line 24, in _parse
    return JsonResponse(response)
  File "/Users/faria/.virtualenvs/orbit/lib/python2.7/site-packages/auth0/v3/authentication/base.py", line 47, in __init__
    super().__init__(response.status_code, content)
TypeError: super() takes at least 1 argument (0 given)

**Comment by sungkim1qbit** [comment]
Having same issue here
```
In [6]: token=get_token.client_credentials(mgmt_client_id,
   ...:                                          mgmt_client_secret,
   ...:                                          'https://{}/api/v2/'.format(dom
   ...: ain))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-ebc89ea40d2e> in <module>()
      1 token=get_token.client_credentials(mgmt_client_id,
      2                                          mgmt_client_secret,
----> 3                                          'https://{}/api/v2/'.format(domain))

/usr/local/lib/python2.7/site-packages/auth0/v3/authentication/get_token.pyc in client_credentials(self, client_id, client_secret, audience, grant_type)
    118                 'grant_type': grant_type,
    119             },
--> 120             headers={'Content-Type': 'application/json'}
    121         )
    122

/usr/local/lib/python2.7/site-packages/auth0/v3/authentication/base.pyc in post(self, url, data, headers)
     10         response = requests.post(url=url, data=json.dumps(data),
     11                                  headers=headers)
---> 12         return self._process_response(response)
     13
     14     def get(self, url, params=None, headers=None):

/usr/local/lib/python2.7/site-packages/auth0/v3/authentication/base.pyc in _process_response(self, response)
     16
     17     def _process_response(self, response):
---> 18         return self._parse(response).content()
     19
     20     def _parse(self, response):

/usr/local/lib/python2.7/site-packages/auth0/v3/authentication/base.pyc in _parse(self, response)
     22             return EmptyResponse(response.status_code)
     23         try:
---> 24             return JsonResponse(response)
     25         except ValueError:
     26             return PlainResponse(response)

/usr/local/lib/python2.7/site-packages/auth0/v3/authentication/base.pyc in __init__(self, response)
     45     def __init__(self, response):
     46         content = json.loads(response.text)
---> 47         super().__init__(response.status_code, content)
     48
     49     def _error_code(self):

TypeError: super() takes at least 1 argument (0 given)
```

**Comment by CDyWeb** [comment]
Fixed by https://github.com/auth0/auth0-python/commit/df71f3daba55fdb2ecfbba8bc9296492283463d3
