### ISSUE TITLE
Auth0Error on Passwordless Object

### ISSUE THREAD

**Issue by wbashir** [auth0/auth0-python#102]
I am getting a `400` ERROR when working with the `from auth0.v3.authentication.passwordless import Passwordless` class as it looks like the `AuthenticationBase` does not set the headers properly for some reason?

Has anyone figured out away to pass the `auth0` class from the documentation so I can just pass my client id only.

``` 
data = {
            'client_id': auth0.clients.domain
        }
        p = Passwordless(data['client_id'])
        o = p.sms(data['client_id'], phone_number) # I get the 400 error here
```

**Comment by lbalmaceda** [comment]
@wbashir Is this still happening? What does the error message say?
