### ISSUE TITLE
Auth0Error no longer provides detailed error messages

### ISSUE THREAD

**Issue by staab** [auth0/auth0-python#105]
On upgrading from 3.1.4 to 3.2.2, error messages from `users.create` went from being helpful like this:

```
Payload validation error: 'Object didn't pass validation for format email: lame_email' on property email (The user's email).
```

To being unhelpful, like this:

```
Bad Request
```

**Comment by lbalmaceda** [comment]
Sorry about that! Are you calling the very same request on both snippets? This changed on April as you can see [here](https://github.com/auth0/auth0-python/commits/master/auth0/v3/management/rest.py). If you could provide the raw response string I might be able to look into what changed. Error handling should have improved in that last release, not the other way around. Maybe the message is still accessible via a different getter method ?

**Comment by staab** [comment]
Sorry I missed your comment! And thanks for the fix.
