### ISSUE TITLE
get all users for an app

### ISSUE THREAD

**Issue by neurochen** [auth0/auth0-python#114]
Hi, Could you please let me know if there is a function to get all the user_id for a specific app? Thanks. 

I want to deploy an app and add new users later on. In this case, I need a function to check all the user_id for authentication status. Thanks.

**Comment by lbalmaceda** [comment]
@neurochen You should be calling the `GET /users` endpoint. This is implemented in [this method](https://github.com/auth0/auth0-python/blob/master/auth0/v3/management/users.py#L27). If you only need to obtain the `user_id` of each user you can narrow the results by passing `fields=user_id`. However if you do need to filter by "application id" that's not something supported out of the box. You'd need to store any extra attributes on the `app_metadata` property of the user (either using Rules or a PATCH) and then filter those locally.
Please note the method uses pagination so you'll need to handle that and request results in a per-page basis.

**Comment by neurochen** [comment]
Thanks! I already figured it out this morning. You guys have the function I need exactly.

Could you please give me a python example for sending a push notification to a specific user and checking the authorization status? I did a bit of search, but still didn't find it. Thanks.

**Comment by lbalmaceda** [comment]
I'm happy you found the method! I don't entirely understand what you mean by "checking the authorization status". Anyway, this space should be used only for this SDK's specific issues or questions. If you need guidance on how to use the auth0 platform please visit https://support.auth0.com where our amazing staff and even the community can help answer you that. I'll close this issue now.
