### ISSUE TITLE
No endpoint/method to revoke the refresh token

### ISSUE THREAD

**Issue by y471n** [auth0/auth0-python#115]
Hi, I couldn't find any method to revoke the refresh token. Isn't it built into the library?

**Comment by lbalmaceda** [comment]
You're looking for the `/oauth/revoke` endpoint but it's missing from this SDK. I'll add an entry in our backlog to review this. Thanks 

Related: https://auth0.com/docs/api/authentication#revoke-refresh-token

**Comment by lifez** [comment]
Can I contribute this?

**Comment by lbalmaceda** [comment]
@lifez go ahead!

**Comment by d3vil0p3r** [comment]
@lifez is this issue taken?

**Comment by lifez** [comment]
Yes I’m working on it

**Comment by joshcanhelp** [comment]
Any news on this one @lifez? Thanks in advance!
