### ISSUE TITLE
Wrap delete_users_by_email

### ISSUE THREAD

**Issue by cancan101** [auth0/auth0-python#121]
It does not look like [`delete_users_by_email`](https://auth0.com/docs/api/management/v2#!/Connections/delete_users_by_email) (aka "Delete a connection user") is currently wrapped by this library.

**Comment by lbalmaceda** [comment]
No, it's not currently available. Following this project's structure the new method should be located in the [connections](https://github.com/auth0/auth0-python/blob/master/auth0/v3/management/connections.py) client. Do you want to make a PR? If not I'll add it to the backlog and we will evaluate with the team.

**Comment by cancan101** [comment]
I don't have time right now to PR this.

**Comment by runz0rd** [comment]
mind if I steal this?

**Comment by lbalmaceda** [comment]
@runz0rd go ahead ! 🥇
