### ISSUE TITLE
Add helper utilities to do token verification

### ISSUE THREAD

**Issue by goodspark** [auth0/auth0-python#162]
Hi,

I've been following the docs on how to use the management API. I got to https://auth0.com/docs/api-auth/tutorials/verify-access-token and had to implement the token verification stuff myself.

My use case right now is:
- Get token
- Verify token
- Manage users

auth0's Python library is already providing most of the flow for me with the exception of the verification step.

It'd be super helpful if the library did this as well!

**Comment by MiniMarvin** [comment]
So you want an automated token verification, right?

**Comment by goodspark** [comment]
Correct. Please let me know if that's a Really Silly Idea. Maybe it is!!

**Comment by ShawnClake** [comment]
Hi @goodspark, I'm entering the realm of Auth0 myself and was wondering if you had built a function or two for the use cases you outlined. If so, any chance you could share them with me? Thanks in advance.

**Comment by joshcanhelp** [comment]
@goodspark - This is definitely something we want in here and have it started in #120. The main thing we're concentrating on is ID tokens but the methods should be usable with Management API tokens as well. If you'd like some guidance on how this can be done, I would take a look at that PR. 

Thanks for the question here! We'll leave this open until that PR is merged.
