### ISSUE TITLE
 Issue with create_email_verification with python 2.7 

### ISSUE THREAD

**Issue by ziaul-haque** [auth0/auth0-python#171]
Hi there,

We are using auth0-python==3.2.2 so long time and thank you very much.

Recently we are facing an issue with create_email_verification method during fresh ticket generation. 

We would like to change the validity of the token but it's not working for us. We have tried with ttl_sec as 600 in secs but token is valid after that period. We have log a issue on auth0 but they didn't find any 
issue with their implementation. 

I am sending you the payload for a request

request payload: {'result_url': 'https://XX.XXXXXXXX.com/activate/account?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYXV0aDB8NWJmY2ZjMjQ0Nzk3ODc0ODczMGE5ZGU4IiwiZW1haWwiOiJhdXRoMF9leHBpcnlfdGVzdGluZ0B0b3BtYWlsLmNvbSJ9.MAQz1Eu295NaVrzp0Alon_U2c6oSxHZxKf_BasEjPUo', 'user_id': u'auth0|5bfcfc2447978748730a9de8', 'ttl_sec': 600}

Response:
{u'ticket': u'https://xxx.xx.auth0.com/lo/verify_email?ticket=xut76imFswr9HNXhrBoJ1j2wnXI53FDM#'}

But this ticket was valid after the duration (ttl_sec: 600). 

Kindly check and let us know if we are missing any implementation.

Thanks

**Comment by lbalmaceda** [comment]
@ziaul-haque the request payload looks fine and it shouldn't fail. In any case, this is not an issue from this SDK but from the API itself and you should contact support via https://support.auth0.com. You mentioned you have reached them and have not received a confirmation of the issue. Do you have a ticket number to share?

**Comment by ziaul-haque** [comment]
@lbalmaceda Thank you very much for your response. Auth0 Ref Ticket# 00415222

Thanks again for your help.

**Comment by lbalmaceda** [comment]
@ziaul-haque It came to my knowledge that the support ticket is still ongoing. I'll close this issue and let you continue the conversation in there.
