### ISSUE TITLE
Example scripts require further setup on Auth0

### ISSUE THREAD

**Issue by mathiesonsterling** [auth0/auth0-python#173]
Following the docs here, wind up with a simple script doing . . . .
```    
        get_token = GetToken(domain)
        token = get_token.client_credentials(non_interactive_client_id,
                                             non_interactive_client_secret, 'https://{}/api/v2/'.format(domain))
        mgmt_api_token = token['access_token']

        auth0 = Auth0(domain, mgmt_api_token)

        conns = auth0.connections.all()
```

However out of the box, with a new Auth0 service, get_token.client_credentials gives 
`
 auth0.v3.exceptions.Auth0Error: 403: Client is not authorized to access "https://
DOMAIN/api/v2/". You might probably want to create a "client-grant" associated to this API. See: https://auth0.com/docs/api/v2#!/Client_Grants/post_client_grants
`

**Comment by lbalmaceda** [comment]
@mathiesonsterling Assuming `domain` as a valid value other than `"DOMAIN"` you need to go to the [APIs](https://manage.auth0.com/#/apis/) section of the dashboard, find the one named `Auth0 Management API` and check in the `Machine to Machine Application` tab that the Application that you're using to call the authN server is authorized, which the right scopes allowed (clicking the arrow)
