### ISSUE TITLE
Async transport support

### ISSUE THREAD

**Issue by hzlmn** [auth0/auth0-python#184]
## Description
Hi, async programming rapidly growing in usage so i am wondered do you consider adding async transport (asyncio/aiohttp) to this library?

**Comment by lbalmaceda** [comment]
Is not in our backlog, no. 
But feel free to drop your feedback or ideas here https://auth0.com/feedback so this reaches the product team. Thanks

**Comment by ca-simone-chiorazzo** [comment]
Any chance to get this feature in the roadmap? Majors python web frameworks support asyncio and at the moment the only way to use auth0-python is wrapping calls with a utility like the `sync_to_async` of [asgiref](https://pypi.org/project/asgiref/)
