### ISSUE TITLE
rotate_secret should be a POST

### ISSUE THREAD

**Issue by jbronstein** [auth0/auth0-python#189]
I'm new to Auth0, so I could definitely be missing something here. I was testing the **clients.rotate_secret** function and noticed it was using a GET request and returning a 404.

https://github.com/auth0/auth0-python/blob/master/auth0/v3/management/clients.py#L135

Based on documentation here, I think this is meant to be a POST.

https://auth0.com/docs/api/management/v2#!/Clients/post_rotate_secret

Hope this helps!

**Comment by lbalmaceda** [comment]
Thanks! @jbronstein It's definitely a `POST`. Do you mind pushing a PR with the change? If so, remember to also update the tests here https://github.com/auth0/auth0-python/blob/e09d69d440362a511d0de3ae7ef90d9a7d950b7b/auth0/v3/test/management/test_clients.py#L122.

**Comment by jbronstein** [comment]
👍 Just made the update, but it looks like I don't have permissions to push anything up to this repo

**Comment by lbalmaceda** [comment]
You need to fork this repo into your own account, commit and push the changes to this remote instead of yours. I'll make that for you as it's quicker.
