### ISSUE TITLE
3.8.1 changelist omits breaking change

### ISSUE THREAD

**Issue by cordery** [auth0/auth0-python#200]
In commit 4a7d304 the return type of AuthenticationBase.get is changed from json to a dict, so for example Users(AUTH0_DOMAIN).userinfo() now returns a dict instead of json.  This is a breaking change and should definitely be in the changelog.

**Comment by lbalmaceda** [comment]
While I understand this could break those parsing the response on their own, the method was not behaving as expected and it was a bug that we did not catch in the past. Apologies for the lack of communication.

I've added a note to the changelog file and tagged it as Breaking Change for more visibility.
