### ISSUE TITLE
Adding typings

### ISSUE THREAD

**Issue by kornicameister** [auth0/auth0-python#208]
# Description

It would be quite useful for this library to support Python with type hints. 
An obvious benefit is that users of the library, if using `mypy` or similar, are able to verify that they are using library in correct way, avoiding situations like:

- typos
- input data mismatch
- output data mismatch

There are 2 ways to do that:
- resolving #207 first and baking annotations directly into codebase as a preferable method mentioned [here](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#adding-a-new-library)
- getting an :+1: from **this** library maintainers and pushing `stubs` into [python/typeshed](https://github.com/python/typeshed) library

Either works for me. I acknowledge that first option requires a lot of thinking and preparation whilst 2nd one is simply easier for `auth0-python` to keep compatibility with older Python versions for a little longer. I am willing to help with either #207 or this issue (either here or in typeshed)

### Prerequisites

- [x] I have checked the [README documentation](https://github.com/auth0/auth0-python/blob/master/README.rst).
- [x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
- [x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0-python/issues) and [PRs](https://github.com/auth0/auth0-python/pulls).
- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
- [x] I am reporting this to the correct repository.

### Environment

-  `auth0-python==3.9.1`
- other factors does not seem to be relevant

### Reproduction

I believe that an example like so is enough:

```python
class TypingShowsAny:
   def __init__(domain: str, access_token: str) -> None:
      self._client = client = auth0.v3.management.Clients(domain, access_token)
      reveal_type(client) 
```

`reveal_type` reports `Any` whilst it should report `auth0.v3.management.Clients`

**Comment by emosenkis** [comment]
Can this be reopened? Type hints would be very nice to have and it's increasingly unusual for an SDK not to either include them or have external stubs in typeshed.

**Comment by miketheman** [comment]
Echoing the sentiments - and tagging @emosenkis and @Widcket as a couple of folks who have recently merged PRs to this library.

**Comment by Widcket** [comment]
cc @adamjmcgrath

**Comment by emosenkis** [comment]
@adamjmcgrath did you see @kornicameister's offer to add community-contributed type hints to typeshed? Would you be amenable to that?

**Comment by adamjmcgrath** [comment]
Thanks for raising that @emosenkis 

And yep, thanks for your offer to add stubs to typeshed @kornicameister - happy to give it a 👍
