### ISSUE TITLE
users.delete returns empty string when successful, also when not successful

### ISSUE THREAD

**Issue by markbenepass** [auth0/auth0-python#212]
### Description

New to Auth0, getting familiar with the management API. Been creating & updating users. Went to delete a user, and ran into apparent bug when on successful delete the Python SDK returns an empty string, with no indication of HTTP 204. So success is ambiguous. Is this expected behavior?

### Reproduction
Using latest version from pip, shows as 3.9.1
`from auth0.v3.management import Auth0`
defined domain and mgmt_api_token
`auth0 = Auth0(domain, mgmt_api_token)`

Successfully creates a new user:
```
new_user = auth0.users.create({
    "email" : "test@getbenepass.com",
    "connection" : "Username-Password-Authentication",
    "password" : "test!1!test",
})
print(new_user)
```
returns sensible object, including the user id

Try to delete that just-created user:
```
delete_user = auth0.users.delete(
    "auth0|*REST_OF_USER_ID_STRING_HERE"
)
```
returns a blank string, but successfully deletes user. Confirmed by listing all the users.

if I then run the same snippet again:
```
delete_user = auth0.users.delete(
    "auth0|*REST_OF_USER_ID_STRING_HERE"
)
```
Nothing happens, because that user doesn't exist, but it returns the same blank string.

Is this expected behavior? Any way to return the HTTP status code? This seems like a potential problem. Thanks!

**Comment by lbalmaceda** [comment]
check the `rest.py` file at the bottom there are some custom Error and Response classes. I'm not sure why the methods are private but those seem to expose the `status_code` of the response.

**Comment by markbenepass** [comment]
Thanks for the tip, will check out

**Comment by lbalmaceda** [comment]
Where you able to confirm if it was a 204?

**Comment by markbenepass** [comment]
Just checked again, using the following:

`delete_user = auth0.users.delete("auth0|user_id_here")`

`type(delete_user)` = <class 'str'>
`print(delete_user)` = empty string

Given the return is a string object, the attributes of a response object won't seem to help here, unless I'm making a mistake

**Comment by lbalmaceda** [comment]
Right. I checked it yesterday and successful responses return the body object and not the response object. You won't be able to access things such as the headers or the status code.
Regarding the deletion of users, I imagine it takes some time for the change to impact the databases and that's why the following response has the same result. If the server rejected the request, an `Auth0Error` exception would be raise.

**Comment by lbalmaceda** [comment]
Closing this as already clarified the SDK behavior.
