### ISSUE TITLE
Add root name support to signup method

### ISSUE THREAD

**Issue by dbinetti** [auth0/auth0-python#229]
### Describe the problem you'd like to have solved

As a developer, I'd like to be able to set the root `name` field on account creation.

### Describe the ideal solution

```
from auth0.v3.authentication import Database
auth0_client = Database(settings.AUTH0_DOMAIN)
auth0_user = auth0_client.signup(
    client_id=settings.AUTH0_CLIENT_ID,
    email=email,
    name=name,     <---- ADDING THIS IS THE IDEAL SOLUTION
    password=password,
    connection='Username-Password-Authentication',
)
```

## Alternatives and current work-arounds

You can update the user instance afterwards (as a second-call).

**Comment by lbalmaceda** [comment]
I see `name` is part of some user profile properties available on the API https://auth0.com/docs/api/authentication#signup. Would it make sense to add an argument `user_profile` with default `None` that we would later extract each of the allowed values and create the request?

**Comment by dbinetti** [comment]
Yes, I think that makes good sense.

**Comment by lbalmaceda** [comment]
I checked with the team. Given that we're already using half of the parameters supported by the API, we could add the remaining ~5 with a default value of `None` (as username). That way it's simpler to invoke (doesn't require an extra dict) and you can send only what you need.

Would you send a PR for us to review?

**Comment by dbinetti** [comment]
Sure, I’ll give it a shot

**Comment by lbalmaceda** [comment]
I also added a PR for this

**Comment by dbinetti** [comment]
Love it!
