### ISSUE TITLE
Docs not available [SDK-1942]

### ISSUE THREAD

**Issue by mwgamble** [auth0/auth0-python#234]
### Description

The docs for this library are not available on the Auth0 website, where documentation for libraries in other languages are present.

https://auth0.com/docs/libraries

**Comment by lbalmaceda** [comment]
Hey, 👋  That's correct, this library does not have a dedicated docs article in the Auth0 site. The basic usage is explained in the readme. Was there a specific use case you needed help with?

**Comment by mwgamble** [comment]
What's the point of the `docs` directory then?

https://github.com/auth0/auth0-python/tree/master/docs

> Was there a specific use case you needed help with?

At the moment, no, because it's very difficult to get an understanding of what the library is capable of at all without published documentation. If I can't tell what the library is capable of at a high level I wouldn't know where to start drilling down to find more details, and therefore have no way of judging if this library is suitable in any way for what I need.

**Comment by lbalmaceda** [comment]
I guess at some point there was an intent to upload them somewhere (e.g. readthedocs.org) but that never happened. I can share with you that we do have a task to host the libraries generated docs but that is targeted for Q4.

The library is built on top of python-requests and has some custom networking classes to handle the response deserialization or any network errors that might occur. As with the rest of our SDKs, 2 core APIs are exposed: The authentication API for logging the user in and the management API for extending what you can typically do on the auth0 dashboard. All methods are documented so if you're making use of an IDE you can see the accepted parameters and returned types with a shortcut. There are basic usage snippets on the readme but again, feel free to reach out if you have a specific use case you need clarification.

**Comment by StigKorsnes** [comment]
Hi there  @lbalmaceda :)
Testing the database module, however hit a 404 on first attempt. Guessing it`s the oauth/ro endpoint that has been deprecated?
A simple hack with replacing oauth/ro with the token endpoint oauth/token does the trick, but I also need to include client_secret with this one. Additionally I`m using audience claim (my api identifier) in order to get a JWT to work with (validation, sub etc). Not sure if I`m using the package wrongly, or if an update is overdue on the package, but hopefully you can give me some guidance? Using it like this :
```
myDBconn=Database(domain=auth0_domain)
token=myDBconn.login(client_id=client_id,
    username="username@gmail.com",
    password="password",
    connection="connection name as on dashboard"
    )
```

**Comment by lbalmaceda** [comment]
@StigKorsnes I'm not the author of the SDK but I think they originally wanted to nest all "username and password" endpoints in there and later figured out it was better to put all the `/oauth/token` routes together in a separate file. The database module as of today should only be used for username/password sign up on auth0 database connections and for sending the email to request a password change.

**Comment by StigKorsnes** [comment]
@lbalmaceda Thanks. Still, the oauth/ro endpoint is depcrecated (and says so in the docs). Is the package being maintained?

**Comment by lbalmaceda** [comment]
@StigKorsnes Why it wasn't removed from this SDK you ask? Doing so would pose a breaking change. So the way forward for this major is to deprecate it and discourage its usage. The next major will remove it, as breaking changes are allowed in new major versions.

The `/oauth/ro` is a legacy endpoint associated with a grant type no longer enabled by default. You [might be able to add it](https://auth0.com/docs/applications/application-grant-types#auth0-legacy-grants) to your client through the management API but I'd encourage you to use the password-realm grant and the `/oauth/token` endpoint that took its place. In this SDK, you can access that [here](https://github.com/auth0/auth0-python/blob/master/auth0/v3/authentication/get_token.py#L117).

**Comment by lbalmaceda** [comment]
@StigKorsnes I haven't tried, but it might be possible to add a legacy grant through the [Management API](https://auth0.com/docs/api/management/v2/#!/Clients/patch_clients_by_id). The server might reject the request if your tenant is too new and doesn't accept legacy grants.

**Comment by mwgamble** [comment]
Not sure why this was marked as stale. Did the documentation end up getting published as planned?

**Comment by lbalmaceda** [comment]
@mwgamble generating the docs on release and publishing them got deprioritized. We're still tracking it internally SDK-1942. For now, please use your preferred IDE shortcut to open the associated pydocs.

**Comment by mwgamble** [comment]
For the second time, this should not have been marked as stale because it's still an issue. It's quite frustrating that I apparently have to monitor this every week in case stale bot decides it's time to speak up.

**Comment by lbalmaceda** [comment]
@mwgamble Apologies for that, Stalebot is configured to close an issue after 3 months of inactivity in the thread, although it should ignore these types of issues. 

I can share that this is still in our backlog (SDK-1942) but not yet prioritized over the other work we have there. If you are able to contribute a PR that can populate that /docs folder with every release of this SDK that we make, I'm happy to take a look at it and leave a review.
