### ISSUE TITLE
Any plans to add the "branding" resource?

### ISSUE THREAD

**Issue by dbinetti** [auth0/auth0-python#249]
### Describe the problem you'd like to have solved

There is a branding resource at https://auth0.com/docs/api/management/v2#!/Branding/get_branding  Any plans to add it to the library?

**Comment by stevehobbsdev** [comment]
Hi, thanks for raising and we appreciate your patience here. We would like to achieve parity across our management SDKs where possible, and this endpoint is something that we should add to this SDK. However, it is low priority and in the meantime you are able to interact with the REST API directly without having this direct support.

We have taken your feedback on board to see how we can improve the SDK in the future.
