### ISSUE TITLE
Send Password Change email to Users.

### ISSUE THREAD

**Issue by defied** [auth0/auth0-python#264]
### Describe the problem you'd like to have solved

I would like to be able to use the API to send password-reset / change emails to users.

### Describe the ideal solution

Email should be sent to users who would then click link and reset their current passwords.

## Alternatives and current work-arounds
Curl.

**Comment by defied** [comment]
Is this repo still active?

**Comment by lbalmaceda** [comment]
Hey @defied, apologies for the delay. I believe the functionality that you want is already covered in the [tickets](https://github.com/auth0/auth0-python/blob/master/auth0/v3/management/tickets.py) entity. If that's not the cause, could you please expand a bit and share links to the specific MGMT API endpoints that you need to get access to? Thanks

**Comment by senhuayu** [comment]
@lbalmaceda I tried the following code:

```
body = {
  "user_id": f'auth0|{user_id}'
}
auth0.tickets.create_pswd_change(body)
```

but didn't receive password change email in the inbox that is associated with the user_id. The object "auth0" is confirmed to work fine.  

How do I correctly define the "body" dictionary to receive the email? Or what else shall I call to receive the email?

**Comment by JakeFDev** [comment]
The create password change ticket endpoint only seems to create the link to reset a password, maybe meant to be sent or used in some way by the calling client and doesn't actually create and send an email by itself.

**Comment by JakeFDev** [comment]
After playing around a bit I got it working and sending an email as expected using the Database class. Hope this helps if there is any confusion here.

I have a base auth0 class where I initiate the db.
```python
    @property
    def database(self) -> Database:
        if self._database is None:
            self._database = Database(self.domain)
        return self._database
```

Then use it elsewhere
```python
    def create_password_change(self, user_id):
        user = User.objects.get(authz_id=user_id)
        self.auth0.database.change_password(
            client_id=self.auth0.client_id,
            email=user.email,
            connection=CONNECTION_NAME
        )
```

Where CONNECTION_NAME is a const 'Username-Password-Authentication'
