### ISSUE TITLE
Returning boolean on token validator

### ISSUE THREAD

**Issue by bisguzar** [auth0/auth0-python#272]
Hi,

I'm using the token validator of the authentication submodule. It's raising a TokenValidationError if validation failed and returning nothing (so the method returning None by python internals) if validation success.

I'm not sure is it a good idea. If I use this method inside an if condition and assume the token is valid the condition won't work. Because it will return None which is equal to False.

In my opinion, the method should return True when a token is validated. And IMHO it should return False instead of raising an error, but it will be a breaking change. So I'm not sure is it necessary.

**Comment by lbalmaceda** [comment]
Returning a boolean value would make it impossible to know what went wrong with the token verification (e.g. what check triggered the failure). The exception that is raised at least has a message describing the issue. I believe this should help while developing or debugging an app. It's probably not helpful during production, as token validation issues are typically related to a wrong configuration/setup.

i.e. something like this
```python
try:
  sv = AsymmetricSignatureVerifier(jwks_url)
  tv = TokenVerifier(signature_verifier=sv, issuer=issuer, audience=client_id)
  tv.verify(id_token)
except TokenValidationError as err:
  print err
```

**Comment by bisguzar** [comment]
Yes, I agree. My point was it is returning None even if all checks passed. I just updated my PR. And it's open for commits by contributors.
