### ISSUE TITLE
Checkpoint Pagination for Roles not supported

### ISSUE THREAD

**Issue by joberdick** [auth0/auth0-python#277]
### Describe the problem

Some pagination no longer works with recent update to Auh0 API's. One example is https://auth0.com/docs/api/management/v2#!/Roles/get_role_user

It now requires checkpoint pagination for over 1000 users, which the SDK does not support. Not sure if there are other cases of this, but this is only one I am aware of. 

### What was the expected behavior?

To be able to query over 1000 objects when supported by the API

### Reproduction
Make a call to get list of role members using: https://github.com/auth0/auth0-python/blob/afe66b8fb6f7d28609c0ec46ae2fa3bf89a8fcae/auth0/v3/management/roles.py#L101

with more than 1000 users. 

Error returned

```
auth0.v3.exceptions.Auth0Error: 400: Requesting page 10 exceeds the allowed maximum of 1000 records. To fetch results beyond 1000, use the checkpoint pagination method.
```

### Environment

using 3.16.2

**Comment by frederikprijck** [comment]
Thanks for reporting this and sorry for the inconvenience!

We are looking into this internally to see what has to happen in the different SDKs and how we can prioritize this.

We will get back to this as soon as possible with more information.

**Comment by evansims** [comment]
Hi @joberdick 👋  Thanks for your patience on this. This issue has been addressed with the addition of checkpoint pagination support in PR #278, and will be shipped in the next release. 👍
