### ISSUE TITLE
AsyncIO support

### ISSUE THREAD

**Issue by ca-simone-chiorazzo** [auth0/auth0-python#304]
Hi,

we've integrated Auth0 in a FastAPI application and at the moment, we're forced to run the requests to Auth0 in a thread pool since the Auth0 library uses `requests` that is IO blocking.

Is there any plan to support AsyncIO?

Running each request in a thread pool is resource-intensive and does not allow us to leverage the non-blocking IO towards Auth0 APIs. In the long term, this will not be maintainable/scalable in our view.

**Comment by ca-simone-chiorazzo** [comment]
I saw that 3 years ago this ticket was issued https://github.com/auth0/auth0-python/issues/184 and closed. But I think that in 3 years the AsyncIO support for python is increased rapidly and is now widely adopted (thanks also to the success of projects like FastAPI/Starlette)

**Comment by chiora93** [comment]
Any news about this request?

**Comment by MwinyiMoha** [comment]
I hope this supports AsyncIO soon

**Comment by adamjmcgrath** [comment]
Hi @ca-simone-chiorazzo (and others who have supported this issue @chiora93 @MwinyiMoha @Giaco9 @krissetto @willianantunes @bradydean)

We have a branch that currently supports asyncio for the Management client (requires `python >=3.6` and `aiohttp`), you can test it out by installing the branch using pip (see https://pip.pypa.io/en/stable/topics/vcs-support/#supported-vcs), eg

```bash
pip install git+https://git.example.com/MyProject.git@master aiohttp
```

Then:

```python
import asyncio
from auth0.v3.management import Auth0

domain = 'myaccount.auth0.com'
mgmt_api_token = 'MGMT_API_TOKEN'

auth0 = Auth0(domain, mgmt_api_token)

async def main():
  # u = auth0.users.all() <= sync
  u = await auth0.users.all_async() # <= async

asyncio.run(main())
```

We would be grateful if you try it out that you let us know how you got on with it

**Comment by ca-simone-chiorazzo** [comment]
Hi @adamjmcgrath,

thanks for the update! I'll try to test it this week, I'll keep you posted on this.

Best regards,
Simone
