### ISSUE TITLE
Flask API Seed example raises InvalidAudienceError('Invalid audience')

### ISSUE THREAD

**Issue by rayvace** [auth0/auth0-python#4]
I notice that Flask API Seed example only works when I pass "audience=CLIENT_ID" into jwt.decode(). I'm not sure if it's something with my configuration, but I consistently hit an InvalidAudienceError when I auth via Google+ if I fail to include this as a parameter.

**Comment by Annyv2** [comment]
Hi! We have updated our sample so the audience is no longer the CLIENT_ID.
