### ISSUE TITLE
Improve Signature of send_verification_email

### ISSUE THREAD

**Issue by cancan101** [auth0/auth0-python#41]
Rather than:

``` python
send_verification_email(self, body)
```

I suggest:

``` python
send_verification_email(self, user_id)
```

**Comment by lbalmaceda** [comment]
There are many signatures on this SDK like that (receiving a super generic dictionary as body). I don't like that at all :D but changing it would be breaking at this point. I've already added a task to track this internally in the eventual case of a new major version being planned. Thanks
