### ISSUE TITLE
Need rate limiting info returned by SDK

### ISSUE THREAD

**Issue by yvonnewilson** [auth0/auth0-python#42]
SDK should return the info that Auth0 returns on HTTP headers about rate limiting, so calling program can dynamically adjust the rate at which it makes subsequent API calls (that are rate limited)

Here is the documentation on what programs are supposed to do:
https://auth0.com/docs/rate-limits

SDK should return the info to enable that.

**Comment by marcelchastain** [comment]
Was looking into this myself. Seems like the SDK just returns a plain dict of the response.

For auth0 core devs, future me, or anyone who might be  interested in developing a PR, one approach would be to use [requests.Session()](http://docs.python-requests.org/en/master/user/advanced/#session-objects) combined with [event hooks](http://docs.python-requests.org/en/latest/user/advanced/?highlight=hooks#event-hooks).

Allowing the user to register their own callback function seems like a big win. Until then, I might just monkeypatch the various requests methods.

**Comment by remi-debette** [comment]
Hi, I just encountered Rate limit issues with the Library.

Would you have a hint on how to tackle this in the library today?

Thank you

**Comment by lbalmaceda** [comment]
👋  @remi-debette I don't know if the persons above can share their implementation, but the issue today is the library doesn't return the "response object" with the information. The only thing that is returned is the parsed response body. So any rate-limiting implementation, that doesn't introduce breaking changes, needs to happen internally in some sort of throttling logic that reads those headers and retries the requests.

**Comment by remidebette** [comment]
(Other account but same perspn) 
Indeed, as today the library raises exceptions in the case of Rate limit reached, my understanding is that there is no such mechanism internally and that we are forced to retry after the fact

**Comment by lbalmaceda** [comment]
Correct, there's no automatic handling or exponential backoff strategy. 

The formatting in the readme is a bit broken, but each request could fail with any of these 3 exceptions listed there https://github.com/auth0/auth0-python#error-handling. You could try/catch this particular `RateLimitError` type and retry after some seconds.

**Comment by leeomara** [comment]
For future users who arrive here searching, rate-limiting info has been exposed as of 3.11, see https://github.com/auth0/auth0-python/pull/219

Also, automatic rate-limit handling has been implemented since 3.17, see https://github.com/auth0/auth0-python/pull/285
