### ISSUE TITLE
TypeError when updating universal login template

### ISSUE THREAD

**Issue by sid-motorq** [auth0/auth0-python#452]
### Describe the problem

Auth0.branding.update_template_universal_login(htmlText) gives TypeError: RestClient.put() got an unexpected keyword argument 'type' 

### What was the expected behavior?

It should update the universal login page

### Reproduction

- call update_template_universal_login() 

update_template_universal_login() is defined as 
`     
    return self.client.put(
                self._url("templates", "universal-login"),
                type="put_universal-login_body",
                body={"template": body},
            )
`

removing the type parameter and changing body to data fixes the issue

### Environment

- **Version of this library used:**
auth0-python==3.24.0

**Comment by adamjmcgrath** [comment]
Thanks for raising this @sid-motorq 

Please continue to use the workaround and we'll take a look when we can
