### ISSUE TITLE
azp must match audience in the python sdk but the react sdk puts the clientid into the azp not the audience

### ISSUE THREAD

**Issue by mcsheehan** [auth0/auth0-python#453]
https://github.com/auth0/auth0-python/blob/cd950b0de275a35b5d4f24eb0151c9c440fff5f6/auth0/v3/authentication/token_verifier.py#L402

Request a token using a SPA and it will put the clientid of the single page application into the azp not the audience.
This makes it tricky to get a token with the react api and validate it with the auth0 python api

**Comment by frederikprijck** [comment]
Hey @mcsheehan ,

The code you refer to is for verifying ID Tokens, which you shouldnt be doing in this case, if I understand things correctly. The code seems correct.

Also important to note, our React SDK doesnt add any azp claim. This is done by Auth0.

In an Id token, the AZP is expected to be set to the `client_id`, which should be the same as the audience in terms of `id token`, but not `access token`.

Are you trying to validate the access token using the class we provide to validate Id tokens? If you are, that's not what you should be doing. 
If you aren't, can you pleae elaborate on what you are trying to achieve?

Thanks

**Comment by adamjmcgrath** [comment]
Closing due to innactivity
