### ISSUE TITLE
Object of type "Auth0" cannot be used with "with" because it does not implement __aenter__ Pylancereport (GeneralTypeIssues)

### ISSUE THREAD

**Issue by Zaffer** [auth0/auth0-python#468]
### Describe the problem

Pylance complaining when trying to use 'with' clause

### What was the expected behavior?

No complaints from pylance

### Reproduction

```python
# To share a session amongst multiple calls to multiple services
async def get_auth0() -> AsyncGenerator:
    async with Auth0(domain, mgmt_api_token) as auth0:
        yield auth0
        # user = await auth0.users.get_async(user_id)
        # connection = await auth0.connections.get_async(connection_id)
```
errors:
"
Object of type "Auth0" cannot be used with "with" because it does not implement __aenter__PylancereportGeneralTypeIssues
Object of type "Auth0" cannot be used with "with" because it does not implement __aexit__PylancereportGeneralTypeIssues
"

![image](https://user-images.githubusercontent.com/51871197/213936483-b3f5da77-20e0-4d73-8af8-cdc59fb63553.png)

### Environment

VSCode using latest pylance with type hints.

- **Version of this library used:** latest version
- **Which framework are you using, if applicable:** FastAPI
- **Other modules/plugins/libraries that might be involved:** na
- **Any other relevant information you think would be useful:** none

**Comment by Viicos** [comment]
See https://github.com/auth0/auth0-python/blob/master/auth0/management/async_auth0.py

**Comment by adamjmcgrath** [comment]
Hi @Zaffer - thanks for raising this

As @Viicos points out `async_auth0.py` has async support and is switched out for `auth0.py` at runtime [here](https://github.com/auth0/auth0-python/blob/master/auth0/management/__init__.py#L32-L35)

You should either ignore that static check, or use `async_auth0.py` if you want to keep that static check.
