### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by Viicos** [auth0/auth0-python#470]
As the project is now supporting Python3.7 and greater, we could add type hints. I'd be happy to work on this if this is an option.

For reference: https://typing.readthedocs.io/en/latest/source/libraries.html

Tracked PRs:

- https://github.com/auth0/auth0-python/pull/472
- https://github.com/auth0/auth0-python/pull/497

**Comment by adamjmcgrath** [comment]
Hi @Viicos - thanks for the offer

We'd be happy to look at a PR, we may choose to limit the completeness of the types depending on the maintenance overhead. (eg typing the arguments required for getting a client by id, great - typing the whole response payload for every request to the management api, not maintainable for us right now)

**Comment by Viicos** [comment]
Yes this is understandable, I'll take a deep look at the repository and describe on this issue where I'll add types
