### ISSUE TITLE
Add support for latest /branding endpoints

### ISSUE THREAD

**Issue by mardav10** [auth0/auth0-python#475]
There are additional endpoints available for **Branding**, `/api/v2/branding/themes` and they are not available in the latest version (4.0.0): 

[Branding/get_default_branding_theme](https://auth0.com/docs/api/management/v2#!/Branding/get_default_branding_theme)

[Branding/get_branding_theme](https://auth0.com/docs/api/management/v2#!/Branding/get_branding_theme)
[Branding/patch_branding_theme](https://auth0.com/docs/api/management/v2#!/Branding/patch_branding_theme)
... and so on

**Comment by mardav10** [comment]
Thank you for adding. When will 4.1.0 be published?

**Comment by adamjmcgrath** [comment]
Hi @mardav10 - just fixing an issue with publishing, should be able to resolve it by the end of the week

**Comment by adamjmcgrath** [comment]
👋 It's published https://github.com/auth0/auth0-python/releases/tag/4.1.0
