### ISSUE TITLE
Outdated Readme.md

### ISSUE THREAD

**Issue by aviel08** [auth0/auth0-python#482]
### Describe the problem

Documentation on Readme.md is outdated.

### Reproduction
```
from auth0.authentication import Database

database = Database('my-domain.us.auth0.com', 'my-client-id')

database.signup(email='user@domain.com', password='secr3t', connection='Username-Password-Authentication')
```
The above code produces: 
`ModuleNotFoundError: No module named 'auth0.authentication'`

I think it should be:

```
from auth0.v3.authentication import Database

database = Database('my-domain.us.auth0.com')

database.signup(email='user@domain.com', password='secr3t', connection='Username-Password-Authentication', client_id ='client_id')
```
Same for the rest of the examples. Login requires `token.login` to pass scope and audience.

I'm using Python 3.9 and the latest pip install auth0-python

**Comment by marcusmotill** [comment]
v3 folder was removed in the [4.0.0 release](https://github.com/auth0/auth0-python/releases/tag/4.0.0) docs seem correct for those using v4

**Comment by aviel08** [comment]
That is correct, I must have installed V3 before and `pip install auth0-python` will not upgrade to the latest version unless specified, my bad, but If I run the example for login:

```
from auth0.authentication import GetToken

token = GetToken('my-domain.us.auth0.com', 'my-client-id', client_secret='my-client-secret')

token.login(username='user@domain.com', password='secr3t', realm='Username-Password-Authentication')
```
I get:
`TypeError: login() missing 2 required positional arguments: 'scope' and 'audience'`
I have `auth0_python-4.1.0-py2.py3-none-any.whl`

**Comment by githubisagit** [comment]
Have run into same exact problem.
