### ISSUE TITLE
Worse developer experience since introducing async support - IntelliSense doesn't work for endpoint classes

### ISSUE THREAD

**Issue by michaeloliverx** [auth0/auth0-python#483]
Some background first:
I used this SDK in a previous company with a very positive experience, fast forward a few years I find myself working with auth0 in python again only to find that the DX is much worse :(

### Describe the problem

It looks like since the introduction of `asyncio` support that the attributes are dynamically added:
https://github.com/auth0/auth0-python/blob/947a768617ef3c93a30c7d8579270c14ba9745f2/auth0/management/auth0.py#L81-L87

This doesn't play well with static analysis thus there is no autocomplete / intellisense for any of the endpoint classes.

<img width="540" alt="image" src="https://user-images.githubusercontent.com/55017335/226332477-41d0f05d-e8d4-4850-bd09-f562a907c4eb.png">

<img width="291" alt="image" src="https://user-images.githubusercontent.com/55017335/226332557-9f25be7c-7178-4595-9e7f-f9ec9254e468.png">

This also means that type checking via mypy / pyright etc doesn't work.

### What was the expected behavior?

I expect all the endpoint classes to be listed as attributes.

This was the behaviour of v3.22.0:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/55017335/226333798-bee46112-6de9-4725-bde1-18935517897a.png">

### Reproduction

```python
from auth0.management import Auth0

auth0_client = Auth0("", "")

auth0_client.users
```

### Environment

- **Version of this library used:** 4.1.0
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by marcusmotill** [comment]
Agreed, also making pylint go wild:
![image](https://user-images.githubusercontent.com/7673106/226453961-2c24f6f2-556a-457c-86c6-03687be1bfe5.png)

**Comment by mardav10** [comment]
+1

**Comment by michaeloliverx** [comment]
> Hi,
> 
> I'm currently working on adding types to this sdk (on my free time). Once #472 gets merged, I'll continue working on the `management` module, and I'll be able to fix this.

Nice work on getting that started, but I also think its important for the core team to embrace type hints for it to be successful. If there is no type checking in the CI then the type hints could quickly become out of date, wrong type hints are worse than none.


For the core team it might be worth investigating some sort of codegen solutions if the maintenance of the types is too much e.g. https://github.com/Azure/autorest / https://github.com/Azure/autorest.python

**Comment by Viicos** [comment]
I've added a `mypy` configuration file in the linked PR, taking into account the fact that maintainers can't fully keep return types (e.g. with `TypedDict`) up to date. CI will probably be updated once I'll finish working on typing

**Comment by adamjmcgrath** [comment]
Hi @michaeloliverx - thanks for raising this

The `_async` methods are added at runtime so not available for static analysis, other than that we have not made any other changes to the SDK that should make it worse in terms of DX.

> For the core team it might be worth investigating some sort of codegen solutions if the maintenance of the types is too much e.g. https://github.com/Azure/autorest / https://github.com/Azure/autorest.python

We are investigating codegen solutions for a next major, but for the time being the async methods will remain as they are.

**Comment by adamjmcgrath** [comment]
Ah, ok - thanks for clarifying @michaeloliverx

And thanks for providing a fix @Viicos - I was away last week and am catching up with a few things, but will take a look at your PR as soon as I can

**Comment by marcusmotill** [comment]
can we reopen this? the issue is not resolved.

**Comment by adamjmcgrath** [comment]
Sure - have raised https://github.com/auth0/auth0-python/pull/486 to fix
