### ISSUE TITLE
Management.Branding.update_template_universal_login - Syntax Error!

### ISSUE THREAD

**Issue by metarama** [auth0/auth0-python#494]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-python#readme) and [Examples](https://github.com/auth0/auth0-python/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0-python.readthedocs.io/en/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-python/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The Management.Branding.update_template_universal_login method is defined as follows:

```
def update_template_universal_login(self, body):
        return self.client.put(
            self._url("templates", "universal-login"),
            body={"template": body},
        )
```

The keyword argument 'body=' should be 'data=' to match the RestClient.put method. 
I get a Python runtime error.

`TypeError: put() got an unexpected keyword argument 'body'.`

### Reproduction

Simply invoke Branding.update_template_universal_login() with some simple html text.

### auth0-python version

3.9

### Python version

3.9

**Comment by adamjmcgrath** [comment]
Thanks for raising this @metarama - have raised https://github.com/auth0/auth0-python/pull/495 to fix
