### ISSUE TITLE
Connections.all() should accept name

### ISSUE THREAD

**Issue by esantora** [auth0/auth0-python#496]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-python#readme) and [Examples](https://github.com/auth0/auth0-python/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0-python.readthedocs.io/en/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-python/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I would like this library to have closer parity with the Auth0 Management API, especially when it comes to available parameters. The Connections.all() method should accept a `name` argument to retrieve a Connection by name.

### Describe the ideal solution

The Connections.all() method should accept a `name` argument to retrieve a Connection by name.

### Alternatives and current workarounds

Retrieve all connections and iterate through results to see if a Connection name matches.

**Comment by adamjmcgrath** [comment]
Thanks for raising this @esantora 

Yep - will schedule some work to include this, in the meantime you can use `connections.all({ "extra_params": { "name": "my-name" } })`
