### ISSUE TITLE
Method from documentation missing

### ISSUE THREAD

**Issue by screamz2k** [auth0/auth0-python#503]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-python#readme) and [Examples](https://github.com/auth0/auth0-python/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0-python.readthedocs.io/en/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-python/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello :)
In the documentation at https://auth0-python.readthedocs.io/en/latest/v3.authentication.html#auth0.v3.authentication.users.Users.tokeninfo it says, there's a method to get user infos using the jwt token. But this method does not exist anymore. How do i now get the user info?

### Reproduction

Look at documentation: https://auth0-python.readthedocs.io/en/latest/v3.authentication.html#auth0.v3.authentication.users.Users.tokeninfo

### auth0-python version

4.3.0

### Python version

3.11.3

**Comment by adamjmcgrath** [comment]
Hi @screamz2k - thanks for raising this, looks like our docs publishing has stopped working, let me raise some work to fix

For userinfo, you want:

```py
from auth0.authentication import Users

u = Users("my.domain.com")
u.userinfo(access_token="atk")
```

**Comment by screamz2k** [comment]
![image](https://github.com/auth0/auth0-python/assets/78593516/82630b8d-af7a-4e44-9870-5c901c36631f)
Now nothing is displayed.

**Comment by screamz2k** [comment]
yes, thank you :)
