### ISSUE TITLE
Retries implementation of rest.py missing for POST/PATCH/PUT/DELETE

### ISSUE THREAD

**Issue by tlotter** [auth0/auth0-python#513]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-python#readme) and [Examples](https://github.com/auth0/auth0-python/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0-python.readthedocs.io/en/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-python/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

If you make a lot of API calls after each other, you will run into Error Code 429 of GlobalRateLimit.

Only **GET** implements retries, as you can see here: https://github.com/auth0/auth0-python/blob/8e1bf4a0ff07db16a768acf2b8b4310b523f03f1/auth0/rest.py#L139-L178

The retry implementation for **POST/FILE_POST/PATCH/PUT/DELETE** is missing, as you can see here:
https://github.com/auth0/auth0-python/blob/8e1bf4a0ff07db16a768acf2b8b4310b523f03f1/auth0/rest.py#L180-L239

### Reproduction

Try the following script to do a lot of POST call. (I used adding a member to an Organization)

```
# =========================================================
# Step 1: Install Auth0 Phyton SDK
# =========================================================
"""
pip install auth0-python
"""

# =========================================================
# Step 2: Create M2M Application
# =========================================================
"""
1. Go to "Applications" -> "Applications" and click on "+ Create Application".
2. Enter as "Name": "SaaS Management M2M", select "Machine to Machine Applications" and click on "Create".
3. Select "Auth0 Management API" and select "All" Permissions (for production, select only the scopes that are required).
4. Click on "Authorize"
5. Switch to the tab "Settings" and copy the values of "Domain", "Client ID" and "Client Secret".
"""

# =========================================================
# Step 3: Run Deployment
# =========================================================
from auth0.authentication import GetToken
from auth0.management import Auth0
from auth0.rest import RestClientOptions
from auth0.rest import RateLimitError
import time

# Step 1: Get Access Token for Management API
auth0_domain = "domain.eu.auth0.com"
auth0_client_id = "XXXX"
auth0_client_secret = "XXXX"

get_token = GetToken(auth0_domain, auth0_client_id, client_secret=auth0_client_secret)
token = get_token.client_credentials('https://{}/api/v2/'.format(auth0_domain))
mgmt_api_token = token['access_token']

# Step 2: Create Auth0
rest_client_option = RestClientOptions(retries=10) # set max retries to maximum of 10
auth0 =  Auth0(auth0_domain, mgmt_api_token, rest_client_option)

# Step 3: Loop on any API that is doing a put/post/delete call for about 30 tries,
# for me - it usually happens on try 16 or 17
for i in range(1, 30):
    start_time = time.perf_counter()
    print("===== Iteration "+ str(i) + " =====")
    try:
        organization_id = "org_V6RnNQ9x3vKcGcB9"
        user_id = "auth0|64db3cf0cf71fa8ca0ae9226"
        auth0.organizations.create_organization_members(organization_id, {"members":[user_id]})
    except RateLimitError as e:
        print("!!!!!!!!!!!! RateLimitError !!!!!!!!!!!!")
        print("Time per API call: " + str(time.perf_counter() - start_time))
        raise e
    
    print("Time per API call: " + str(time.perf_counter() - start_time))
```

### auth0-python version

4.4.0

### Python version

3.11.4

**Comment by adamjmcgrath** [comment]
Thanks for raising this @tlotter - will take a look
