### ISSUE TITLE
Type checks started failing on our codebase with v4.4

### ISSUE THREAD

**Issue by lorinkoz** [auth0/auth0-python#514]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-python#readme) and [Examples](https://github.com/auth0/auth0-python/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0-python.readthedocs.io/en/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-python/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

No complaints on v4.3, automatic upgrade PR on v4.4 fails like this:

<img width="633" alt="Screenshot 2023-08-18 at 08 53 26" src="https://github.com/auth0/auth0-python/assets/3628106/00338725-a3a5-4bc1-a041-c31bb75a57d1">

Example of the code:

```
import auth0.management as _management

token = get_token_from_somewhere()
auth0 = _management.Auth0(API_DOMAIN, token)

users = auth0.users_by_email.search_users_by_email(...)
```

### Reproduction

[Nothing useful to add here]

### auth0-python version

4.4

### Python version

3.11

**Comment by adamjmcgrath** [comment]
Thanks @lorinkoz - will take a look

**Comment by dazzag24** [comment]
I'm also seeing this issue after just updating to 4.4

**Comment by lorinkoz** [comment]
Thanks for fixing so quickly! Do you plan to do a patch release for this change alone or do you normally wait for a few more fixes before cutting a release?

**Comment by adamjmcgrath** [comment]
Np @lorinkoz - will ship a patch today

**Comment by adamjmcgrath** [comment]
@lorinkoz - apologies - it might take a little longer while I fix a releasing issue

Will update this thread when the patch is up

**Comment by adamjmcgrath** [comment]
@lorinkoz [4.4.1](https://github.com/auth0/auth0-python/releases/tag/4.4.1) is now available - lmk if you run into any more types issues in the management client

**Comment by lorinkoz** [comment]
Good day. FYI, the problem remains. I just checked the PR and it seems to be adjusting the mypy config for this repo, but this doesn't have any effect on projects using the package.

**Comment by adamjmcgrath** [comment]
Ah, ok - thanks for the heads up @lorinkoz 

@Viicos - do you know a fix for this?

**Comment by Viicos** [comment]
Well this looks similar to https://github.com/auth0/auth0-python/issues/483 but for the `AsyncAuth0` class. Can be fixed by either doing the same thing as:

https://github.com/auth0/auth0-python/blob/b10cd5b0547e3e1ab22b9664713ea419ca09444c/auth0/management/auth0.py#L54-L94

Or by doing it in a `TYPE_CHECKING` block

**Comment by adamjmcgrath** [comment]
@Viicos We add async variants to every method in the management client at runtime - eg `users.get_async(id)` would all of these not also need to be defined? can we just opt out of type checking for `AsyncAuth0`?

**Comment by Viicos** [comment]
Looking at how it is done currently:

https://github.com/auth0/auth0-python/blob/d1097e783f9e89de2177a879c83b93a4d2faf090/auth0/management/async_auth0.py#L30-L42

And the fact that `asyncify` returns dynamic stuff as well, it is indeed hard to type check this correctly.

The fix you did on https://github.com/auth0/auth0-python/pull/515 only affects the current project, as the `mypy.ini` file is only used when working on `auth0-python`. Instead, projects depending on `auth0-python` need disable this `attr-defined` error code on their mypy configuration if they want to ignore the error (this means that https://github.com/auth0/auth0-python/pull/515 can be reverted)

**Comment by adamjmcgrath** [comment]
> Instead, projects depending on auth0-python need to disable this attr-defined error code on their mypy configuration

I don't think It's reasonable to expect users of this package to have to do this, if there isn't a better solution I'm going to have to remove the `py.typed` file and revert publishing types until a better solution is available.

**Comment by lorinkoz** [comment]
Thanks again!
