### ISSUE TITLE
Cannot install when python version is set like ">=3.10" in pyproject.toml

### ISSUE THREAD

**Issue by ka7eh** [auth0/auth0-python#517]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-python#readme) and [Examples](https://github.com/auth0/auth0-python/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0-python.readthedocs.io/en/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-python/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

It seems the latest changes in 4.4.1 in requirements.txt (https://github.com/auth0/auth0-python/blob/4.4.1/requirements.txt) causes issue if python version is specified like ">=..." in pyproject.toml.

This is the error I'm getting when I try to add this package with poetry:

```
The current project's Python requirement (>=3.10) is not compatible with some of the required packages Python requirement:
  - auth0-python requires Python >=3.7,<4.0, so it will not be satisfied for Python >=4.0

Because no versions of auth0-python match >4.4.1,<5.0.0
 and auth0-python (4.4.1) requires Python >=3.7,<4.0, auth0-python is forbidden.
So, because fastapi-auth0 depends on auth0-python (^4.4.1), version solving failed.
``` 

### Reproduction

1. Start a new python project with the following in pyproject.toml:
```
[tool.poetry]
name = "auth0"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
2. Add `auth0-python` with poetry (tested with poetry v1.6.1): `poetry add auth0-python`.

### auth0-python version

4.4.1

### Python version

3.10

**Comment by evansims** [comment]
Hi @ka7eh 👋 Thanks for the heads up, I'll investigate and get back to you.
