### ISSUE TITLE
userinfo_async broken in 4.6.0

### ISSUE THREAD

**Issue by Cruppelt** [auth0/auth0-python#558]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-python#readme) and [Examples](https://github.com/auth0/auth0-python/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0-python.readthedocs.io/en/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-python/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

await userinfo_async doesn't properly resolve the coroutine.

### Reproduction

`
from auth0.asyncify import asyncify
from auth0.authentication import Users as AuthUsers

U = asyncify(AuthUsers)
u = U(domain=AUTH0_DOMAIN)
user_info = await u.userinfo_async(token)
`

### Additional context

Works fine with 4.5.0

### auth0-python version

4.6.0

### Python version

3.11.4

**Comment by adamjmcgrath** [comment]
hi @Cruppelt - thanks for raising this

This should be fixed when in `4.6.1` which should be released shortly #559
