### ISSUE TITLE
Get all Rules regardless of enabled/disabled

### ISSUE THREAD

**Issue by beck3905** [auth0/auth0-python#70]
The Auth0 Management API supports getting all Rules or filtering by enabled/disabled.  If the enabled parameter is present and set to True, only enabled rules are returned.  If it is present and set to False, only disabled rules are returned.  If it is not present, all rules are returned.

The python package always includes the enabled parameter in requests and thus will only return enabled rules if set to True (default) or disabled rules if set to False.  There is no way to get all Rules in a single request via the Python package.

I've created a pull request that addresses this issue.

**Comment by Annyv2** [comment]
Thank you very much for your contribution! We have merged your PR
