### ISSUE TITLE
There was a change to auth0/v3/authentication/logout.py on 6/9/2017 that makes this library incompatible with Python 2.7

### ISSUE THREAD

**Issue by beck3905** [auth0/auth0-python#71]
It appears the following commit ([https://github.com/auth0/auth0-python/commit/7b0c7b123942a99af358dfb07815ed71ac3b7c9b](https://github.com/auth0/auth0-python/commit/7b0c7b123942a99af358dfb07815ed71ac3b7c9b)) broke Python 2.7 support as the `urllib.parse` method is `urlparse` in Python 2.7.

**Comment by vCloudernBeer** [comment]
I would like to take a look at this problem and submit a pull request when fixed.

**Comment by vCloudernBeer** [comment]
Seems like it is already fixed.
latest code:
try:
    from urllib.parse import quote_plus
except ImportError:
from urllib import quote_plus
