### ISSUE TITLE
Calls to requests.get() and requests.post() are missing the timeout parameter

### ISSUE THREAD

**Issue by Substr** [auth0/auth0-python#82]
We've encountered issues in our production environment for weeks and after some digging, released that calls to `requests.get()` and `requests.post()` and missing the `timeout` parameter, causing the server to hang indefinitely on occasion if no response is received.

In our specific case, the problem is with these instances:

```
class AuthenticationBase(object):
    def post(self, url, data=None, headers=None):
        response = requests.post(url=url, data=json.dumps(data),
                                 headers=headers)
        return self._process_response(response)

    def get(self, url, params=None, headers=None):
        return requests.get(url=url, params=params, headers=headers).text
```

but there may well be others.

As noted on the [requests documentation](http://docs.python-requests.org/en/master/user/quickstart/#timeouts):

> Nearly all production code should use this parameter in nearly all requests. Failure to do so can cause your program to hang indefinitely

**Comment by rmnvncnt** [comment]
Using the code from the example calls to `get_token.client_credentials()` hangs forever.

**Comment by Sytten** [comment]
Could Auth0 prioritize that, it's an easy why for not much effort.

**Comment by goodspark** [comment]
I don't think this should be closed.

**Comment by Sytten** [comment]
Yeah I didn't have the time to work on the PR for that issue, we fixed it in our project by setting a global requests timeout.

**Comment by goodspark** [comment]
This stale bot is kinda incentivizing the wrong thing.

**Comment by Sytten** [comment]
I will get to fix my PR sometime this month

**Comment by Sytten** [comment]
Not stale

**Comment by lbalmaceda** [comment]
The timeout parameter should already be present and used in the get/post methods. https://github.com/auth0/auth0-python/blob/master/auth0/v3/authentication/base.py#L17-L20
