### ISSUE TITLE
Add support for new get_users_by_email endpoint

### ISSUE THREAD

**Issue by chrisbroome** [auth0/auth0-python#84]
The auth0 node.js client got support for the [get_users_by_email](https://auth0.com/docs/api/management/v2#!/Users_By_Email/get_users_by_email) about 3 weeks ago (https://github.com/auth0/node-auth0/commit/80c9b0c7039a73a5c69af23756f589904e4e80a8).

This is pretty critical for us because the way we are currently searching for users (using the [get_users](https://auth0.com/docs/api/management/v2#!/Users/get_users) API with `search_engine=v2` and `q=some-user@example.com`) no longer works.

**Comment by wbashir** [comment]
Any updates to this?

**Comment by dkvasnicka** [comment]
Use the `Users.list` method, it supports v2 search engine and the `q` parameter: https://github.com/auth0/auth0-python/blob/master/auth0/v3/management/users.py#L27

**Comment by saltukalakus** [comment]
@dkvasnicka no, that is a different endpoint. search by email endpoint is recommended instead of that endpoint where possible. I have pushed a PR => https://github.com/auth0/auth0-python/pull/96 hopefully will be merged soon.

**Comment by saltukalakus** [comment]
cc @aaguiarz

**Comment by lbalmaceda** [comment]
@chrisbroome Following up here while the new endpoint's PR is ongoing. The new `search_engine=v3` should perform fine when querying a User in the `GET /users` endpoint.

**Comment by chrisbroome** [comment]
I'm actually actually no longer on the project that uses this repo, so I'm fine with closing out the issue.

**Comment by joshcanhelp** [comment]
Addressed in #96
