### ISSUE TITLE
Auth0Error not raise with Users Client

### ISSUE THREAD

**Issue by Calion54** [auth0/auth0-python#86]
Hi, 

I would like update the user password but if the request return a 400 status code, there is no exception throw "Auth0Error".

My request : 

```
request = auth0.users.update(<id>, {
            "password": "totototo"
        })
```

I get : 
`{'statusCode': 400, 'error': 'Bad Request', 'message': 'PasswordHistoryError: Password has previously been used'}`

But in your RestClient, you check if there is an attribute with the name "errorCode" but that doesn't work because the attribute is called "statusCode".

```
if isinstance(text, dict) and 'errorCode' in text:
    raise Auth0Error(status_code=text['statusCode'],
                             error_code=text['errorCode'],
                             message=text['message'])
```

is it normal ???

**Comment by lbalmaceda** [comment]
This should be already fixed on the latest release.
