### ISSUE TITLE
How can I use the Auth0Error class

### ISSUE THREAD

**Issue by saschajullmann** [auth0/auth0-python#91]
Hi there,

I'm trying to use the Auth0 Python SDK in my flask application but can't get the Auth0Error to work. I currently have the following code:

`import os, json, requests
from auth0.v3.authentication import GetToken
from auth0.v3.exceptions import Auth0Error
from auth0.v3.management import Auth0

auth_domain = os.getenv('DOMAIN')
auth_client_id = os.getenv('AUTH0_CLIENT_ID')
auth_client_secret = os.getenv('AUTH0_CLIENT_SECRET')

def get_token():
    get_token = GetToken(auth_domain)
    token = get_token.client_credentials(
        auth_client_id,
        auth_client_secret,
        'https://{}/api/v2/'.format(auth_domain))
    return token['access_token']

def create_user(token, data):
    try:
        user = auth0.users.create(data)
        return user
    except Auth0Error:
       ????
`

I'm importing the functions in my route function (flask). The get_token function works as expected and creating a new user also works fine. However when I try to test my route with wrong user data I can't capture the Auth0Error... how can I extract the status code and error message from the "Auth0Error exception"? What do I have to put where the questions marks are in order to get a meaningful error?

**Comment by cricket007** [comment]
```python
except Auth0Error as e:
    print(e.status_code) 
```

https://docs.python.org/3/tutorial/errors.html

**Comment by saschajullmann** [comment]
Thank you!
