### ISSUE TITLE
Mis-encoded unicode in blocked account message

### ISSUE THREAD

**Issue by larkost-fetch** [auth0/auth0-python#95]
I am pretty sure that the actual problem is on the server side, but since I am seeing it through the Python client I am filing this here.

I am seeing and issue with the error message returned when a user has been blocked for too many authentication attempts. Namely that there is a mis-encoded right-single-quote (as in the right curly quote) in the message:
```python
 Unauthorized(u'Could not authorize with auth0 due to too_many_attempts: Your account has been blocked after multiple consecutive login attempts. We\u2019ve sent you an email with instructions on how to unblock it.',)
```
That is what you get if you print it with `%r`, if you try to just print it (so `%s`) you get:
```python
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 207: ordinal not in range(128)
```

There really is no need for Unicode in the error messages, so please change that. And I think that your server is also probably mis-encoding in this case.

**Comment by lbalmaceda** [comment]
Thanks. I've already reported this. Let's see what happens 🤞

**Comment by d3vil0p3r** [comment]
@lbalmaceda can I take this?

**Comment by larkost-fetch** [comment]
@joshcanhelp Is this closed because it was fixed?

**Comment by joshcanhelp** [comment]
@larkost-fetch - I didn't check with the server team on whether this was fixed on their end or not but it's not related to this SDK, as you said, and I think keeping it open is a bit confusing (see the comment above).

**Comment by lbalmaceda** [comment]
@larkost-fetch Rest assure this is tracked and will be fixed soon. But like @joshcanhelp mentioned, the message response is given to this SDK by the server.
